// URL-safe slug, identical to the SQL lx_slugify() in migration 089 so a slug
// computed in code matches one generated by the DB trigger. Used for any
// app-side slug needs (e.g. building canonical links from a name).

export function slugify(input: string): string {
  const s = (input ?? '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '')
  return s === '' ? 'vendor' : s
}
