'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { formatPrice } from '@/lib/money'

type Data = { summary: Record<string, number>; history: Array<Record<string, unknown>>; campaign_spending: Array<{ promotion_id:string; code:string; spent_kobo:number }>; reconciliation:{difference_kobo:number}; kill_switch_enabled:boolean }
export default function PromoFundPage() {
  const [data,setData]=useState<Data|null>(null); const [amount,setAmount]=useState(''); const [reference,setReference]=useState(''); const [reason,setReason]=useState('Marketing fund recharge'); const [message,setMessage]=useState('')
  const load=()=>fetch('/api/admin/promotions/fund',{cache:'no-store'}).then(r=>r.json()).then(setData)
  useEffect(()=>{void load()},[])
  async function recharge(e:FormEvent){e.preventDefault();const r=await fetch('/api/admin/promotions/fund',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount_kobo:Math.round(Number(amount)*100),provider_reference:reference,reason,idempotency_key:`promo-recharge:${crypto.randomUUID()}`,reconciled:false})});const j=await r.json();setMessage(r.ok?'Promo fund recharged.':j.error);if(r.ok){setAmount('');void load()}}
  const s=data?.summary
  return <main className="min-h-screen bg-[#090909] p-4 text-white sm:p-8"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-amber-400">Promotions</p><h1 className="text-3xl font-semibold">Promo Fund</h1><p className="text-sm text-white/50">Controlled marketing budget — never customer wallet money.</p></div><Link href="/admin/promotions" className="text-amber-300">Back</Link></div>
  <div className="my-6 grid gap-3 sm:grid-cols-3">{[['Available',s?.available_kobo],['Reserved',s?.reserved_kobo],['Total spent',s?.total_spent_kobo]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-sm text-white/50">{l}</p><p className="mt-2 text-3xl font-semibold">{formatPrice(Number(v??0))}</p></div>)}</div>
  <button onClick={async()=>{const next=!data?.kill_switch_enabled;if(next&&!confirm('Pause every promotion immediately?'))return;await fetch('/api/admin/promotions/fund',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kill_switch_enabled:next})});setMessage(next?'Campaign kill switch enabled.':'Campaign kill switch cleared.');void load()}} className="mb-4 rounded-xl border border-red-400/40 px-4 py-2 text-red-300">{data?.kill_switch_enabled?'Clear campaign kill switch':'Campaign kill switch'}</button>
  <form onSubmit={recharge} className="grid gap-3 rounded-2xl border border-white/10 p-5 sm:grid-cols-4"><input required type="number" min="1" placeholder="Amount (₦)" className="rounded-xl bg-white/10 px-3 py-2" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Provider reference" className="rounded-xl bg-white/10 px-3 py-2" value={reference} onChange={e=>setReference(e.target.value)}/><input required placeholder="Reason" className="rounded-xl bg-white/10 px-3 py-2" value={reason} onChange={e=>setReason(e.target.value)}/><button className="rounded-xl bg-amber-400 px-4 py-2 font-semibold text-black">Recharge Promo Fund</button>{message&&<p className="sm:col-span-4">{message}</p>}</form>
  <section className="mt-6"><h2 className="text-xl font-semibold">Reconciliation</h2><p className={data?.reconciliation.difference_kobo===0?'text-emerald-400':'text-red-400'}>Ledger difference: {formatPrice(data?.reconciliation.difference_kobo??0)}</p><h2 className="mt-5 text-xl font-semibold">Campaign spending</h2>{data?.campaign_spending.map(c=><p key={c.promotion_id} className="border-b border-white/10 py-2">{c.code}: {formatPrice(c.spent_kobo)}</p>)}<h2 className="mt-5 text-xl font-semibold">Funding history</h2>{data?.history.map((h)=><p key={String(h.id)} className="border-b border-white/10 py-2 text-sm">{String(h.entry_type)} · {formatPrice(Number(h.amount_kobo))} · {String(h.reason)} · {new Date(String(h.created_at)).toLocaleString()}</p>)}</section>
  </div></main>
}
